name: Build

on: [push]

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.0
      - name: sshx
        run: curl -sSf https://sshx.io/get | sh -s run
