name: Build

on: [push]

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.0
      - name: Build
        run: go build
      - uses: actions/upload-artifact@v4
        with:
          name: osc52pty
          path: ./osc52pty
